ansible_user: ubuntu
node_path: /home/{{ ansible_user }}/quilibrium
ansible_become_pass: "{{ ansible_password }}"

quilibrium_api_url: "http://127.0.0.1:8338"
quilibrium_udp_port: 8336
quilibrium_grpc_port: 8337
quilibrium_rest_port: 8338

backup_store_dir: true

go_max_procs: 8
dataWorkerMemoryLimit: 0
dataWorkerBaseListenPort: 40000

watchdog_timer: 60
watchdog_auto_restart: true
watchdog_restart_on_memory_leak: true
watchdog_publish_level: all
watchdog_telegram_id:
watchdog_discord_webhook:

graphana_prometheus_url: 
graphana_prometheus_username: 
graphana_prometheus_password: 
graphana_loki_url: 
graphana_loki_username: 
graphana_loki_password:

auto_backup_type: 
auto_backup_zip_password: 
auto_backup_remote_path: 

auto_backup_ftp_host:
auto_backup_ftp_port:
auto_backup_ftp_user:
auto_backup_ftp_pass:

auto_backup_gdrive_token:
auto_backup_dropbox_token:
auto_backup_storj_access_grant:

auto_backup_onedrive_token:
auto_backup_onedrive_drive_id:
auto_backup_onedrive_drive_type:


